apiVersion: v1
kind: Pod
metadata: 
  name: vproapp
  labels:
    app: vproapp
spec:
  containers:
    - name: appcontainer
      image: imranvisualpath/freshtomapp
      ports: 
        - name: vrpoapp-port
          containerPort: 8080

#container port is exposed port, not port mapping