apiVersion: v1
kind: Service
metadata: 
  name: hello-service
spec:
  ports:
    - port: 8090
      nodePort: 30001
      targetPort: vrpoapp-port
      protocol: TCP
  selector:
    app: vproap
  type: NodePort

#nodeport from 30k and up
#target port is name of port or port no